baseURL = "https://redrat.com.br/"
languageCode = "en-us"
title = "Joubert RedRat"
theme = "researcher"
enableEmoji = true
googleAnalytics = "G-82P3DH8MYV"

[params]
  author = "Joubert RedRat"
  description = "Software Engineer, DevOps, Cosplayer, Speaker, Open-source community evangelist"
  favicon = "assets/favicon/favicon.ico"
  [params.style]
    pageWidth = "850px"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Contents"
    url = "/contents"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 3
  [[menu.main]]
    name = "Donations"
    url = "/donations"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true
