baseURL = "https://joubertredrat.github.io/"
languageCode = "en-us"
title = "Joubert RedRat Site"
theme = "ezhil"

copyright = "$currentYear © Joubert RedRat"

[params]
    subtitle = "Software Engineer, DevOps, Cosplayer, Speaker, Open-source community evangelist"