baseURL = "https://joubertredrat.github.io/"
languageCode = "en-us"
title = "Joubert RedRat"
theme = "researcher"

[params]
    author = "Olivier Roques"
    description = "Software Engineer, DevOps, Cosplayer, Speaker, Open-source community evangelist"
    favicon = "/assets/favicon.ico"