baseURL = "https://joubertredrat.github.io/"
languageCode = "en-us"
title = "Joubert RedRat"
theme = "researcher"

[params]
    author = "Joubert RedRat"
    description = "Software Engineer, DevOps, Cosplayer, Speaker, Open-source community evangelist"
    favicon = "assets/favicon/favicon.ico"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 3
  [[menu.main]]
    name = "Donations"
    url = "/donations"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true
